version: '3.8'

services:
  skohit-music:
    image: skohit/skohit-music:latest
    container_name: skohit-music
    ports:
      - "7000:7000"
    environment:
      - METING_API_URL=${METING_API_URL}
      - APP_VERSION=${VERSION:-latest}
    volumes:
      # 持久化数据目录
      - ./data:/app/data
      # 环境变量文件
      - ./.env:/app/.env
    restart: unless-stopped
